language: generic

services:
  - docker
sudo: false

git:
  submodules: true

env:
#  - OS=centos DIST=6
  - OS=centos DIST=7

install: false

script:
  - if [ -n "$TRAVIS_TAG" ] && [ -n "$OS" ]; then git clone https://github.com/packpack/packpack.git packpack; fi
  - if [ -n "$TRAVIS_TAG" ] && [ -n "$OS" ]; then VERSION=${TRAVIS_TAG:1} packpack/packpack; fi

